apiVersion : apps/v1
kind: Deployment  
metadata:
  name: consumer-deployment 
  namespace: messaging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: himatejaawsdevops/consumer:v17
          ports:
            - containerPort: 8080
          env:
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq.messaging.svc.cluster.local:5672"
            - name: QUEUE_NAME
              value: "task_queue"

