apiVersion : apps/v1
kind: Deployment  
metadata:
  name: producer-deployment 
  namespace: messaging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: himatejaawsdevops/producer:v17
          ports:
            - containerPort: 8080
          env:
            - name: RABBITMQ_USER
              value: "user"
            - name: RABBITMQ_PASSWORD
              value: "password"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq.messaging.svc.cluster.local:5672"
            - name: QUEUE_NAME
              value: "task_queue"
